export const INSERTSELLITEMDATA = "INSERTSELLITEMDATA";
export const INSERTSELLITEM_SUCCESS = "INSERTSELLITEM_SUCCESS";
export const INSERTSELLITEM_FETCH_ERR = "INSERTSELLITEM_FETCH_ERR";
export const INSERTSELLITEM_FETCH_END = "INSERTSELLITEM_FETCH_END";
